force-app/main/default/objects/Account/fields/AG_Lead__c.field-meta.xml
<CustomField>
    <fullName>AG_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/AG_Status__c.field-meta.xml
<CustomField>
    <fullName>AG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AG_Intake__c/AG_Intake__c.object-meta.xml
<CustomObject>
    <label>Intake</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Intake Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intakes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AG_Intake__c/fields/AG_Client__c.field-meta.xml
<CustomField>
    <fullName>AG_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Intakes (Client)</relationshipLabel>
    <relationshipName>Intakes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AG_Service__c/AG_Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>S-{0000000000}</displayFormat>
        <label>Service ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AG_Service__c/fields/AG_From_Date__c.field-meta.xml
<CustomField>
    <fullName>AG_From_Date__c</fullName>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AG_Service__c/fields/AG_Service_Name__c.field-meta.xml
<CustomField>
    <fullName>AG_Service_Name__c</fullName>
    <label>Service Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AG_Service__c/fields/AG_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>AG_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AG_Service_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AG_Service__c/fields/AG_To_Date__c.field-meta.xml
<CustomField>
    <fullName>AG_To_Date__c</fullName>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AG_Service_Line_Item__c/AG_Service_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Service Line Item</label>
    <nameField>
        <displayFormat>SL-{0000000000}</displayFormat>
        <label>Service Line Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AG_Service_Line_Item__c/fields/AG_Intake__c.field-meta.xml
<CustomField>
    <fullName>AG_Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>AG_Intake__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AG_Service_Line_Item__c/fields/AG_Service__c.field-meta.xml
<CustomField>
    <fullName>AG_Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>AG_Service__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AG_Service_Line_Item__c/fields/AG_Service_Request__c.field-meta.xml
<CustomField>
    <fullName>AG_Service_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Request</label>
    <referenceTo>AG_Service_Request__c</referenceTo>
    <relationshipLabel>Service Line Items</relationshipLabel>
    <relationshipName>Service_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AG_Service_Request__c/AG_Service_Request__c.object-meta.xml
<CustomObject>
    <label>Service Request</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Service Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AG_Service_Request__c/fields/AG_Intake__c.field-meta.xml
<CustomField>
    <fullName>AG_Intake__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Intake</label>
    <referenceTo>AG_Intake__c</referenceTo>
    <relationshipLabel>Service Requests</relationshipLabel>
    <relationshipName>Service_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AG_Service_Request__c/fields/AG_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>AG_Service_Type__c</fullName>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Basic Needs</fullName>
            </value>
            <value>
                <fullName>Adults</fullName>
            </value>
            <value>
                <fullName>Children and Families</fullName>
            </value>
            <value>
                <fullName>Older Adults</fullName>
            </value>
            <value>
                <fullName>Person with Special Needs</fullName>
            </value>
            <value>
                <fullName>Teens and Young Adults</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AG_Service_Request__c/fields/AG_Status__c.field-meta.xml
<CustomField>
    <fullName>AG_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Started</fullName>
                <default>true</default>
                <label>Started</label>
            </value>
            <value>
                <fullName>In Assessment</fullName>
            </value>
            <value>
                <fullName>In service</fullName>
            </value>
            <value>
                <fullName>Discharged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/AG_Service_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Adults</fullName>
        <default>true</default>
        <label>Adults</label>
    </customValue>
    <customValue>
        <fullName>Basic Needs</fullName>
    </customValue>
    <customValue>
        <fullName>Children and Families</fullName>
    </customValue>
    <customValue>
        <fullName>Older Adults</fullName>
    </customValue>
    <customValue>
        <fullName>Person with Special Needs</fullName>
    </customValue>
    <customValue>
        <fullName>Teens and Young Adults</fullName>
    </customValue>
    <description>Global picklist for service request and service</description>
    <masterLabel>Service Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AG_Human_Service_CL.cls
public with sharing class AG_Human_Service_CL {

    @AuraEnabled
    public static String findServiceRequest(Id recordId){
        try{
            AG_Service_Request__c serviceRequest = getServiceRequestDetails(recordId);
            return '{"success": true, "data": '+JSON.serialize(serviceRequest)+'}';
        }
        catch(Exception e){
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            return '{"success": false, "message": "'+e.getMessage()+'"}';
        }
    }

    public static AG_Service_Request__c getServiceRequestDetails(Id recordId){
        try{
            String query = 'SELECT Id, AG_Status__c FROM AG_Service_Request__c WHERE Id =: recordId';
            return Database.query(query);
        }
        catch(Exception e){
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            return null;
        }
    }

    @AuraEnabled
    public static string waitListLead( Id recordId, String status){
        try{
            Lead lead = [SELECT Id, Name, Status  FROM Lead WHERE Id =: recordId];
            lead.status = status;
            update lead;

            return '{"success" : true, "message" : "Lead waitlisted successfully"}';
        }
        catch(Exception e){
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            return '{"success": false, "message": "'+e.getMessage()+'"}';
        }
    }

    @AuraEnabled
    public static string dischargeClient( Id recordId, String status){
        try{
            AG_Service_Request__c serviceRequest = [SELECT Id, Name, AG_Intake__c, AG_Status__c  FROM AG_Service_Request__c WHERE Id =: recordId];
            serviceRequest.AG_Status__c = status;
            update serviceRequest;

            Account account = [SELECT Id, AG_Status__c, (SELECT Id FROM Intakes2__r WHERE Id =: serviceRequest.AG_Intake__c) FROM Account];
            account.AG_Status__c = status;
            update account;

            return '{"success" : true, "message" : "Client discharged successfully"}';
        }
        catch(Exception e){
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            return '{"success": false, "message": "'+e.getMessage()+'"}';
        }
    }

    @AuraEnabled
    public static string changeStatusForLead( Id recordId, String status){
        try{
            Lead lead = [SELECT Id, Name, Phone, Status  FROM Lead WHERE Id =: recordId];
            lead.status = status;
            update lead;

            Account account = new Account();
            account.Name = lead.Name;
            account.Phone = lead.Phone;
            account.AG_Lead__c = lead.Id;
            account.Type = 'Customer - Direct';
            account.AG_Status__c = 'Intake';
            insert account;

            AG_Intake__c intake = [SELECT Id, AG_Client__c FROM AG_Intake__c ORDER BY createdDate DESC LIMIT 1];
            intake.AG_Client__c = account.Id;
            update intake;

            Task task = new Task();
            task.Description = 'A lead has been converted to account and was intaken';
            task.Subject = 'Lead intaken process done by' +' '+UserInfo.getName();
            task.ActivityDate = System.today();
            task.Status = 'Completed';
            task.WhatId = account.Id;
            task.Priority = 'High';
            insert task;

            return '{"success" : true, "data" : '+JSON.serialize(intake)+'}';
        }
        catch(Exception e){
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            return '{"success": false, "message": "'+e.getMessage()+'"}';
        }
    }

    @AuraEnabled
    public static string getServiceRequest(Id intakeId){
        try {
            AG_Service_Request__c serviceRequest = [SELECT Id, Name, AG_Service_Type__c FROM AG_Service_Request__c WHERE AG_Intake__c =: intakeId];
            return '{"success" : true, "data" : '+JSON.serialize(serviceRequest)+'}';
        }
        catch(Exception e){
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            return '{"success": false, "message": "'+e.getMessage()+'"}';
        }
    }

    @AuraEnabled
    public static string getServicesForServiceType(String searchKey, String serviceType){
        try {
            String key = '%' + searchKey + '%';
            List<AG_Service__c> services = [SELECT Id, Name, AG_Service_Name__c, AG_Service_Type__c FROM AG_Service__c WHERE AG_Service_Name__c LIKE : key AND AG_Service_Type__c = : serviceType];
            return '{"success" : true, "data" : '+JSON.serialize(services)+'}';
        }
        catch(Exception e){
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            return '{"success": false, "message": "'+e.getMessage()+'"}';
        }
    }

    @AuraEnabled
    public static string saveServiceLineItem(Id intakeId, Id serviceId, Date fromDate, Date toDate){
        try {
            AG_Service_Line_Item__c serviceLineItem = new AG_Service_Line_Item__c();
            serviceLineItem.AG_Intake__c = intakeId;
            serviceLineItem.AG_Service__c = serviceId;
            serviceLineItem.AG_From_Date__c = fromDate;
            serviceLineItem.AG_To_Date__c = toDate;
            insert serviceLineItem;
            return '{"success": true, "data" : '+JSON.serialize(serviceLineItem)+', "message": "Service line item created successfully"}';
        }
        catch(Exception e){
            System.debug(e.getLineNumber());
            System.debug(e.getMessage());
            return '{"success": false, "message": "'+e.getMessage()+'"}';
        }
    }
}